'use strict';
/* L2: self-hosted fonts. Fetches the exact woff2 subsets the app needs from
   Google Fonts ONCE (dev machine, build time), embeds them as data-URI
   @font-face rules between markers in thesismaster.html's <style>, and
   removes any runtime dependency on fonts.googleapis.com — which both
   violated the no-remote-assets spirit and exposed visitor IPs to Google
   (a GDPR finding, docs/AUDIT-baseline.md L2).

   Trims (documented decisions, re-run with edited URLS to change):
   - Amiri: 400 + 700 only (Arabic italic is typographically atypical;
     synthesized oblique is acceptable) — saves ~140KB embedded.
   - IBM Plex Sans Arabic: 400 + 700 (500/600 resolve to nearest) — ~120KB.
   - Latin families keep latin + latin-ext (Turkish İşğ live in latin-ext).

   Licenses: Fraunces, Manrope, IBM Plex Mono, IBM Plex Sans Arabic, Amiri
   are all SIL OFL 1.1 — self-hosting/embedding is permitted; record in
   docs/IP-INVENTORY.md.

   Usage: node tools/embed-fonts.js   (then run the validation gate + copy) */

const fs = require('fs');
const path = require('path');

const HTML = path.join(__dirname, '..', 'thesismaster.html');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const URLS = [
  'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Manrope:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500&display=swap',
  'https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=IBM+Plex+Sans+Arabic:wght@400;700&display=swap',
];
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'arabic']);
const START = '/* ===== EMBEDDED FONTS — generated by tools/embed-fonts.js, do not hand-edit ===== */';
const END = '/* ===== END EMBEDDED FONTS ===== */';

async function fetchText(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error('fetch failed ' + r.status + ': ' + url);
  return r.text();
}
async function fetchBytes(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error('fetch failed ' + r.status + ': ' + url);
  return Buffer.from(await r.arrayBuffer());
}

function parseBlocks(css) {
  // css2 output: /* subset */\n@font-face { ... } repeated
  const out = [];
  const re = /\/\* ([a-z-]+) \*\/\s*@font-face\s*\{([\s\S]*?)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const body = m[2];
    const g = (name) => { const mm = body.match(new RegExp(name + ':\\s*([^;]+);')); return mm ? mm[1].trim() : ''; };
    out.push({
      subset: m[1],
      family: (g('font-family') || '').replace(/['"]/g, ''),
      style: g('font-style') || 'normal',
      weight: g('font-weight') || '400',
      unicodeRange: g('unicode-range'),
      url: (body.match(/url\((https:[^)]+)\)/) || [])[1],
    });
  }
  return out;
}

(async () => {
  let blocks = [];
  for (const u of URLS) blocks = blocks.concat(parseBlocks(await fetchText(u)));
  blocks = blocks.filter(b => KEEP_SUBSETS.has(b.subset) && b.url);
  // skip latin glyphs of the Arabic families — Latin text uses the Latin families
  blocks = blocks.filter(b => !(/Amiri|Arabic/i.test(b.family) && b.subset !== 'arabic'));

  // group: variable families list one block per weight sharing one file —
  // collapse to a single @font-face with a weight range so the base64
  // payload is embedded exactly once
  const groups = new Map();
  for (const b of blocks) {
    const key = [b.family, b.style, b.subset, b.url].join('|');
    if (!groups.has(key)) groups.set(key, { ...b, weights: [] });
    groups.get(key).weights.push(...String(b.weight).split(/\s+/).map(Number));
  }

  const dataByUrl = new Map();
  let rawTotal = 0;
  for (const g of groups.values()) {
    if (!dataByUrl.has(g.url)) {
      const bytes = await fetchBytes(g.url);
      rawTotal += bytes.length;
      dataByUrl.set(g.url, bytes.toString('base64'));
      console.log((bytes.length / 1024).toFixed(0).padStart(4) + ' KB  ' + g.family + ' ' + g.style + ' ' + g.subset);
    }
  }

  const css = [START];
  for (const g of groups.values()) {
    const lo = Math.min(...g.weights), hi = Math.max(...g.weights);
    css.push('@font-face{font-family:\'' + g.family + '\';font-style:' + g.style +
      ';font-weight:' + (lo === hi ? lo : lo + ' ' + hi) +
      ';font-display:swap;src:url(data:font/woff2;base64,' + dataByUrl.get(g.url) +
      ') format(\'woff2\');unicode-range:' + g.unicodeRange + '}');
  }
  css.push(END);

  let html = fs.readFileSync(HTML, 'utf8');
  const startIdx = html.indexOf(START), endIdx = html.indexOf(END);
  if (startIdx > -1 && endIdx > -1) {
    html = html.slice(0, startIdx) + css.join('\n') + html.slice(endIdx + END.length);
  } else {
    const styleAt = html.indexOf('<style>');
    if (styleAt === -1) throw new Error('no <style> tag');
    html = html.slice(0, styleAt + 7) + '\n' + css.join('\n') + html.slice(styleAt + 7);
  }
  fs.writeFileSync(HTML, html);
  console.log('embedded ' + groups.size + ' @font-face rules, ' + (rawTotal / 1024).toFixed(0) + ' KB woff2 (' +
    (rawTotal * 4 / 3 / 1024).toFixed(0) + ' KB as base64). Now remove the fonts.googleapis <link> tags if present, run the validation gate, and copy to public/.');
})();
